## `then`
> `then`函数可以返回一个`promise`，那么这个`promise`就会代替当前`promise`的状态，等到新的`promise`的状态修改时，下一个`then`才会执行

```js
const p1 = new Promise((resolve, reject) =>{
    resolve('p1')
})
const p2 = new Promise((resolve, reject) =>{
  setTimeout(() =>{
    resolve('p2')
  },3000)
})
p1.then(res => {
  console.log(res)
    return p2
}).then(res =>{
    console.log(res)
})

```
## `catch`
### 1. 作用
可以捕获到`promise`程序执行中的`error`，等同于  `.then(null, rejection)`  或  `.then(undefined, rejection)`
### 2. 可以获取到的错误
+ `promise`函数体中抛出的`error`。**在`promise` `resolve`后，再抛出错误，不会被捕获**
     ```js
    const p1 = new Promise((resolve,reject) => {throw new Error('error')})
    p1.catch(error => console.log(error))   // Error: error
    ```
+ `promise`的`reject`操作
    ```js
    const p2 = new Promise((resolve,reject) => reject('rejected'))
    p2.catch(error => console.log(error))  // rejected
    ```
+ `then` 函数体中抛出的`error`
    ```js
    const p3 = new Promise((resolve,reject) => resolve('resolved'))
    p3.then(res =>{
        throw new Error('error')
    }).catch(error => console.log(error))  // Error: error
    ```
+ `then`函数可以返回一个`promise`(如果没有定义catch方法)，如果这个`promise`函数体中有`reject`或者`error`，也可以捕获到

### 3. 推荐使用`catch`方式捕获错误，而不是`then`的第二个参数：
因为`catch`可以捕获到它前面所有`then`方法中的错误

## `finally`
+ 不管promise最后状态如何，都会执行的操作
+ 没有参数，获取不到当前`promise`最后的状态
  

## `Promise.all`
### 1. 参数
+ 参数不仅仅可以是数组，具有Iterator接口的对象都可以。
+ 数组参数的每一个元素为promise实例，如果不是，就会调用Promise.resolve转换为Promise实例
     ```js
    const obj = {
        [Symbol.iterator]() {
            let index = 0
            return {
                next() {
                    return {
                        // promise对象 和 其他类型都可以
                        value: new Promise(resolve => resolve(index++)), done: index > 2
                        // value: index++, done: index > 2
                    }
                }
            }
        }
    }
    const p = Promise.all(obj)
    p.then(res => {
        console.log(res)  // [0, 1]
    })  
    ```
### 2. 状态
```js
const p = Promise.all([p1, p2, p3]);
```
p的状态由p1、p2、p3决定，分成两种情况：
+ **只有p1、p2、p3的状态都变成fulfilled，p的状态才会变成fulfilled**，此时p1、p2、p3的返回值组成一个数组，传递给p的回调函数。
+ **只要p1、p2、p3之中有一个被rejected，p的状态就变成rejected**，此时第一个被reject的实例的返回值，会传递给p的回调函数。
### 3. `catch`
如果参数中的promise定义了catch方法，那么Promise.all()的catch就不会捕获到错误

## `Promise.race`
+ **只要p1、p2、p3之中有一个实例率先改变状态，p的状态就跟着改变**。那个率先改变的 Promise 实例的返回值，就传递给p的回调函数。
+ 参数、`catch`规则同`Promise.all`

## `Promise.resolve`
> 将现有对象转为`Promise`对象。
### 1. 参数
+ 参数为promise实例：原封不动的返回这个实例。
+ 参数为thenable对象：将它转为promise对象，然后立即执行它的then方法
+ 参数不是thenable对象，或者是一个原始值：返回一个新的promise对象，状态为resolved
+ 没有参数：直接返回衣蛾resolved状态的promise对象

## Promise.reject
> 返回一个状态为rejected的promise实例
> 
`Promise.reject()`方法的参数，会原封不动地作为reject的理由，变成后续方法的参数
```js
const thenable = {
  then(resolve, reject) {
    reject('error');
  }
};

Promise.reject(thenable)
.catch(e => {
  console.log(e === thenable)
})
// true  e并不是'error'
```